language: node_js
node_js:
  - "5.1"

env:
  CXX=g++-4.8
  IONIC_VERSION=3.9.2
  CORDOVA_VERSION=6.5.0

install:
  - npm install -g cordova@$CORDOVA_VERSION ionic@$IONIC_VERSION
  - npm install

script:
  - npm run build
  - cordova platform add android
  - cordova prepare