sudo: required

language: node_js
node_js:
  - "5.1"

services:
  - docker

before_install:
- docker pull fixitapp/ionic
- docker run -v $(pwd):/root/fixitapp/ fixitapp/ionic /bin/sh -c "cd /root/fixitapp; cordova platform add android"
- docker ps -a

script:
  - docker run -v $(pwd):/root/fixitapp/ fixitapp/ionic /bin/sh -c "cd /root/fixitapp; npm run build"
  - docker run -v $(pwd):/root/fixitapp/ fixitapp/ionic /bin/sh -c "cd /root/fixitapp; cordova prepare"